## Numpy

It is fundamental library for scientific computing in python . It provides support for arrays and matrices,along with a collection of mathematical functions to  operate on these data structures.

In [10]:
!pip install numpy


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
import numpy as np

## create a array using numpy 
## create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [12]:

arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)   ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [17]:
arr2 = np.array([[1, 2, 3, 4, 5]])
arr2.shape

(1, 5)

In [25]:
array = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(array)
print(array.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [28]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
array1 = np.array([[1,2,3],[4,5,6]])

print("Array: \n",array1)
print("Shape: " , array1.shape)
print("Number of dimensions :" , array1.ndim)
print("Number of size :" , array1.size)
print("Data Type:" ,array1.dtype)
print("Item size :" , array1.itemsize)



Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions : 2
Number of size : 6
Data Type: int64
Item size : 8


In [35]:
###  Numpy Vectorized Operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

### Element Wise addition

print("Addition:" , arr1+arr2)


###  Element Wise substraction


print("Addition:" , arr1-arr2)


### Element Wise multiplication

print("Multiplication:" , arr1*arr2)


##3 Element wise divison

print("Division :" ,arr1/arr2)


Addition: [11 22 33 44 55]
Addition: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division : [0.1 0.1 0.1 0.1 0.1]


In [36]:
## universal Function 

arr = np.array([2,3,4,5,6])

## Square root 

print(np.sqrt(arr))

## Exponential

print(np.exp(arr))


## Sine

print(np.sin(arr))

## natural log 

print(np.log)



[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
<ufunc 'log'>


## Pandas 

It is generally data manipulation library in python,data cleaning and for data analysis 

In [37]:
!pip install pandas 

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 1.6 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/11.5 MB 2.1 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/11.5 MB 2.3 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/11.5 MB 2.1 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/11.5 MB 2.1 MB/s eta 0:00:05
   ------ --------------------------------- 1.8/11.5 MB 1.5 MB/s eta 0:00:07
   -------- ------------------------------- 2.4/11.5 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 2.6/11.5 MB 1.6 MB/s eta 0:00:06
   --------- ------------------------------ 2.6/11.5 MB 1.6 MB/s eta 0:00:06
   --------- ------------------------------ 2.6/11.5 MB 1.6 MB/s eta 0:00:06
   --------- ------------------------------ 2.6/11.5 MB 1.6 MB/s eta 0:00:06
   ----------


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [38]:
import pandas as pd 

In [39]:
##  Pandas series

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n" , series)

Series 
 0    1
1    2
2    3
3    4
4    5
dtype: int64


In [40]:
## create a series from dictionary 

data = {'a':1 , 'b':2 ,'c':3 }
series_dict = pd.Series(data)
print(series_dict)


a    1
b    2
c    3
dtype: int64


In [41]:
data = [10,20,30]
index = ['a' , 'b','c']

pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [42]:
# Dataframe 

##  Create a dataframe from a dic

data = {
    'Name':['Sneha','Vishal','Vilas'] ,
    'Age' :[22,25,52] ,
    'City' :["Sheffield","Liverpool" ,"Ghaziabad"]
}

df = pd.DataFrame(data)
print(df)
print(type(df))


     Name  Age       City
0   Sneha   22  Sheffield
1  Vishal   25  Liverpool
2   Vilas   52  Ghaziabad
<class 'pandas.core.frame.DataFrame'>


In [43]:
import numpy as np
np.array(df)

array([['Sneha', 22, 'Sheffield'],
       ['Vishal', 25, 'Liverpool'],
       ['Vilas', 52, 'Ghaziabad']], dtype=object)

In [44]:
df = pd.read_csv('sales_dataset.csv')
print(df)

       InvoiceNo StockCode   Description  Quantity  UnitPrice  CustomerID  \
0         221958  SKU_1964     White Mug        38       1.71     37039.0   
1         771155  SKU_1241     White Mug        18      41.25     19144.0   
2         231932  SKU_1501    Headphones        49      29.11     50472.0   
3         465838  SKU_1760     Desk Lamp        14      76.68     96586.0   
4         359178  SKU_1386     USB Cable       -30     -68.11         NaN   
...          ...       ...           ...       ...        ...         ...   
49777     354083  SKU_1562      Blue Pen        25      70.92     51445.0   
49778     296698  SKU_1930     USB Cable         7      51.74     28879.0   
49779     177622  SKU_1766  Office Chair        43      85.25     21825.0   
49780     701213  SKU_1602      Notebook        48      39.64     43199.0   
49781     772215  SKU_1832     White Mug        30      38.27     53328.0   

              Country  Discount  PaymentMethod  ShippingCost     Category  

In [47]:
df.head(5)

InvoiceNo StockCode Description  Quantity  UnitPrice  CustomerID  \
0     221958  SKU_1964   White Mug        38       1.71     37039.0   
1     771155  SKU_1241   White Mug        18      41.25     19144.0   
2     231932  SKU_1501  Headphones        49      29.11     50472.0   
3     465838  SKU_1760   Desk Lamp        14      76.68     96586.0   
4     359178  SKU_1386   USB Cable       -30     -68.11         NaN   

          Country  Discount  PaymentMethod  ShippingCost     Category  \
0       Australia  0.470000  Bank Transfer         10.79      Apparel   
1           Spain  0.190000        paypall          9.51  Electronics   
2         Germany  0.350000  Bank Transfer         23.03  Electronics   
3     Netherlands  0.140000        paypall         11.08  Accessories   
4  United Kingdom  1.501433  Bank Transfer           NaN  Electronics   

  SalesChannel  ReturnStatus ShipmentProvider WarehouseLocation OrderPriority  
0     In-store  Not Returned              UPS            London        Medium  
1       Online  Not Returned              UPS              Rome        Medium  
2       Online      Returned              UPS            Berlin          High  
3       Online  Not Returned       Royal Mail              Rome           Low  
4     In-store  Not Returned            FedEx               NaN        Medium

In [48]:
## Acessing the data 
df

InvoiceNo StockCode   Description  Quantity  UnitPrice  CustomerID  \
0         221958  SKU_1964     White Mug        38       1.71     37039.0   
1         771155  SKU_1241     White Mug        18      41.25     19144.0   
2         231932  SKU_1501    Headphones        49      29.11     50472.0   
3         465838  SKU_1760     Desk Lamp        14      76.68     96586.0   
4         359178  SKU_1386     USB Cable       -30     -68.11         NaN   
...          ...       ...           ...       ...        ...         ...   
49777     354083  SKU_1562      Blue Pen        25      70.92     51445.0   
49778     296698  SKU_1930     USB Cable         7      51.74     28879.0   
49779     177622  SKU_1766  Office Chair        43      85.25     21825.0   
49780     701213  SKU_1602      Notebook        48      39.64     43199.0   
49781     772215  SKU_1832     White Mug        30      38.27     53328.0   

              Country  Discount  PaymentMethod  ShippingCost     Category  \
0           Australia  0.470000  Bank Transfer         10.79      Apparel   
1               Spain  0.190000        paypall          9.51  Electronics   
2             Germany  0.350000  Bank Transfer         23.03  Electronics   
3         Netherlands  0.140000        paypall         11.08  Accessories   
4      United Kingdom  1.501433  Bank Transfer           NaN  Electronics   
...               ...       ...            ...           ...          ...   
49777           Spain  0.200000    Credit Card          8.96  Electronics   
49778   United States  0.230000  Bank Transfer         23.55  Electronics   
49779        Portugal  0.200000  Bank Transfer         16.26    Furniture   
49780  United Kingdom  0.310000        paypall         28.56      Apparel   
49781          France  0.100000    Credit Card          9.13   Stationery   

      SalesChannel  ReturnStatus ShipmentProvider WarehouseLocation  \
0         In-store  Not Returned              UPS            London   
1           Online  Not Returned              UPS              Rome   
2           Online      Returned              UPS            Berlin   
3           Online  Not Returned       Royal Mail              Rome   
4         In-store  Not Returned            FedEx               NaN   
...            ...           ...              ...               ...   
49777       Online      Returned              UPS            Berlin   
49778       Online  Not Returned            FedEx         Amsterdam   
49779     In-store  Not Returned            FedEx            London   
49780       Online  Not Returned       Royal Mail            London   
49781       Online  Not Returned              UPS              Rome   

      OrderPriority  
0            Medium  
1            Medium  
2              High  
3               Low  
4            Medium  
...             ...  
49777        Medium  
49778           Low  
49779          High  
49780        Medium  
49781           Low  

[49782 rows x 16 columns]

In [46]:
df.tail(5)

InvoiceNo StockCode   Description  Quantity  UnitPrice  CustomerID  \
49777     354083  SKU_1562      Blue Pen        25      70.92     51445.0   
49778     296698  SKU_1930     USB Cable         7      51.74     28879.0   
49779     177622  SKU_1766  Office Chair        43      85.25     21825.0   
49780     701213  SKU_1602      Notebook        48      39.64     43199.0   
49781     772215  SKU_1832     White Mug        30      38.27     53328.0   

              Country  Discount  PaymentMethod  ShippingCost     Category  \
49777           Spain      0.20    Credit Card          8.96  Electronics   
49778   United States      0.23  Bank Transfer         23.55  Electronics   
49779        Portugal      0.20  Bank Transfer         16.26    Furniture   
49780  United Kingdom      0.31        paypall         28.56      Apparel   
49781          France      0.10    Credit Card          9.13   Stationery   

      SalesChannel  ReturnStatus ShipmentProvider WarehouseLocation  \
49777       Online      Returned              UPS            Berlin   
49778       Online  Not Returned            FedEx         Amsterdam   
49779     In-store  Not Returned            FedEx            London   
49780       Online  Not Returned       Royal Mail            London   
49781       Online  Not Returned              UPS              Rome   

      OrderPriority  
49777        Medium  
49778           Low  
49779          High  
49780        Medium  
49781           Low

In [49]:
df['Description']

0           White Mug
1           White Mug
2          Headphones
3           Desk Lamp
4           USB Cable
             ...     
49777        Blue Pen
49778       USB Cable
49779    Office Chair
49780        Notebook
49781       White Mug
Name: Description, Length: 49782, dtype: object

In [50]:
type(df['Description'])

pandas.core.series.Series

In [57]:
## for row index 

df.loc[1]

InvoiceNo                  771155
StockCode                SKU_1241
Description             White Mug
Quantity                       18
UnitPrice                   41.25
CustomerID                19144.0
Country                     Spain
Discount                     0.19
PaymentMethod             paypall
ShippingCost                 9.51
Category              Electronics
SalesChannel               Online
ReturnStatus         Not Returned
ShipmentProvider              UPS
WarehouseLocation            Rome
OrderPriority              Medium
Name: 1, dtype: object

In [58]:
## columns index

df.iloc[1]

InvoiceNo                  771155
StockCode                SKU_1241
Description             White Mug
Quantity                       18
UnitPrice                   41.25
CustomerID                19144.0
Country                     Spain
Discount                     0.19
PaymentMethod             paypall
ShippingCost                 9.51
Category              Electronics
SalesChannel               Online
ReturnStatus         Not Returned
ShipmentProvider              UPS
WarehouseLocation            Rome
OrderPriority              Medium
Name: 1, dtype: object

In [59]:
## Acessing a specified element
df.at[2,'Description']

'Headphones'

In [60]:
## Acessing a specified element using iat

df.iat[2,2]

'Headphones'

In [61]:
#df

InvoiceNo StockCode   Description  Quantity  UnitPrice  CustomerID  \
0         221958  SKU_1964     White Mug        38       1.71     37039.0   
1         771155  SKU_1241     White Mug        18      41.25     19144.0   
2         231932  SKU_1501    Headphones        49      29.11     50472.0   
3         465838  SKU_1760     Desk Lamp        14      76.68     96586.0   
4         359178  SKU_1386     USB Cable       -30     -68.11         NaN   
...          ...       ...           ...       ...        ...         ...   
49777     354083  SKU_1562      Blue Pen        25      70.92     51445.0   
49778     296698  SKU_1930     USB Cable         7      51.74     28879.0   
49779     177622  SKU_1766  Office Chair        43      85.25     21825.0   
49780     701213  SKU_1602      Notebook        48      39.64     43199.0   
49781     772215  SKU_1832     White Mug        30      38.27     53328.0   

              Country  Discount  PaymentMethod  ShippingCost     Category  \
0           Australia  0.470000  Bank Transfer         10.79      Apparel   
1               Spain  0.190000        paypall          9.51  Electronics   
2             Germany  0.350000  Bank Transfer         23.03  Electronics   
3         Netherlands  0.140000        paypall         11.08  Accessories   
4      United Kingdom  1.501433  Bank Transfer           NaN  Electronics   
...               ...       ...            ...           ...          ...   
49777           Spain  0.200000    Credit Card          8.96  Electronics   
49778   United States  0.230000  Bank Transfer         23.55  Electronics   
49779        Portugal  0.200000  Bank Transfer         16.26    Furniture   
49780  United Kingdom  0.310000        paypall         28.56      Apparel   
49781          France  0.100000    Credit Card          9.13   Stationery   

      SalesChannel  ReturnStatus ShipmentProvider WarehouseLocation  \
0         In-store  Not Returned              UPS            London   
1           Online  Not Returned              UPS              Rome   
2           Online      Returned              UPS            Berlin   
3           Online  Not Returned       Royal Mail              Rome   
4         In-store  Not Returned            FedEx               NaN   
...            ...           ...              ...               ...   
49777       Online      Returned              UPS            Berlin   
49778       Online  Not Returned            FedEx         Amsterdam   
49779     In-store  Not Returned            FedEx            London   
49780       Online  Not Returned       Royal Mail            London   
49781       Online  Not Returned              UPS              Rome   

      OrderPriority  
0            Medium  
1            Medium  
2              High  
3               Low  
4            Medium  
...             ...  
49777        Medium  
49778           Low  
49779          High  
49780        Medium  
49781           Low  

[49782 rows x 16 columns]

In [64]:
##Adding 
##df['Salary'] = [500000,600000,70000000]  # add according to the dataset given 
## to delete the columns
## axis if 0 then it checks row index and 1 is column index
##df.drop('Salary',axis = 0, inplace = True )

In [65]:
df['Quantity']=df['Quantity']+1

In [67]:
df.drop(0 , inplace = True )

In [68]:
df

InvoiceNo StockCode   Description  Quantity  UnitPrice  CustomerID  \
1         771155  SKU_1241     White Mug        19      41.25     19144.0   
2         231932  SKU_1501    Headphones        50      29.11     50472.0   
3         465838  SKU_1760     Desk Lamp        15      76.68     96586.0   
4         359178  SKU_1386     USB Cable       -29     -68.11         NaN   
5         744167  SKU_1006  Office Chair        48      70.16     53887.0   
...          ...       ...           ...       ...        ...         ...   
49777     354083  SKU_1562      Blue Pen        26      70.92     51445.0   
49778     296698  SKU_1930     USB Cable         8      51.74     28879.0   
49779     177622  SKU_1766  Office Chair        44      85.25     21825.0   
49780     701213  SKU_1602      Notebook        49      39.64     43199.0   
49781     772215  SKU_1832     White Mug        31      38.27     53328.0   

              Country  Discount  PaymentMethod  ShippingCost     Category  \
1               Spain  0.190000        paypall          9.51  Electronics   
2             Germany  0.350000  Bank Transfer         23.03  Electronics   
3         Netherlands  0.140000        paypall         11.08  Accessories   
4      United Kingdom  1.501433  Bank Transfer           NaN  Electronics   
5              Sweden  0.480000    Credit Card         13.98  Electronics   
...               ...       ...            ...           ...          ...   
49777           Spain  0.200000    Credit Card          8.96  Electronics   
49778   United States  0.230000  Bank Transfer         23.55  Electronics   
49779        Portugal  0.200000  Bank Transfer         16.26    Furniture   
49780  United Kingdom  0.310000        paypall         28.56      Apparel   
49781          France  0.100000    Credit Card          9.13   Stationery   

      SalesChannel  ReturnStatus ShipmentProvider WarehouseLocation  \
1           Online  Not Returned              UPS              Rome   
2           Online      Returned              UPS            Berlin   
3           Online  Not Returned       Royal Mail              Rome   
4         In-store  Not Returned            FedEx               NaN   
5           Online  Not Returned              DHL            London   
...            ...           ...              ...               ...   
49777       Online      Returned              UPS            Berlin   
49778       Online  Not Returned            FedEx         Amsterdam   
49779     In-store  Not Returned            FedEx            London   
49780       Online  Not Returned       Royal Mail            London   
49781       Online  Not Returned              UPS              Rome   

      OrderPriority  
1            Medium  
2              High  
3               Low  
4            Medium  
5            Medium  
...             ...  
49777        Medium  
49778           Low  
49779          High  
49780        Medium  
49781           Low  

[49781 rows x 16 columns]

In [69]:
print(df.dtypes)

InvoiceNo              int64
StockCode             object
Description           object
Quantity               int64
UnitPrice            float64
CustomerID           float64
Country               object
Discount             float64
PaymentMethod         object
ShippingCost         float64
Category              object
SalesChannel          object
ReturnStatus          object
ShipmentProvider      object
WarehouseLocation     object
OrderPriority         object
dtype: object


In [70]:
df.describe()

InvoiceNo      Quantity     UnitPrice    CustomerID      Discount  \
count   49781.000000  49781.000000  49781.000000  44803.000000  49781.000000   
mean   550687.843334     23.372029     47.538782  55033.273397      0.275744   
std    260701.465182     17.917817     33.479216  25913.809913      0.230077   
min    100005.000000    -49.000000    -99.980000  10001.000000      0.000000   
25%    324552.000000     12.000000     23.600000  32750.500000      0.130000   
50%    552268.000000     24.000000     48.920000  55167.000000      0.260000   
75%    776367.000000     38.000000     74.610000  77307.500000      0.380000   
max    999997.000000     50.000000    100.000000  99998.000000      1.999764   

       ShippingCost  
count  47292.000000  
mean      17.494671  
std        7.220567  
min        5.000000  
25%       11.220000  
50%       17.500000  
75%       23.722500  
max       30.000000

In [72]:
grouped = df.groupby('Country')['Quantity'].mean()

In [73]:
print(grouped)

Country
Australia         23.004624
Belgium           23.359233
France            23.339953
Germany           23.302965
Italy             23.614625
Netherlands       22.998802
Norway            23.241280
Portugal          23.452078
Spain             23.496829
Sweden            23.156495
United Kingdom    23.624402
United States     23.893051
Name: Quantity, dtype: float64
