Word Emebedding (Feature Extraction)

In [36]:
from tensorflow.keras.preprocessing.text import one_hot
import numpy as np



In [37]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]


In [38]:
##  Define the vocabulary size
voc_size = 10000


In [39]:
### One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr


[[3078, 4788, 1119, 5159],
 [3078, 4788, 1119, 8531],
 [3078, 9415, 1119, 5156],
 [3780, 181, 7375, 2522, 2723],
 [3780, 181, 7375, 2522, 4397],
 [9559, 3078, 7203, 1119, 994],
 [8691, 2571, 4567, 2522]]

In [40]:
##  word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences # ("as embedded layer")
from tensorflow.keras.models import Sequential


In [41]:
# Making every sentence of equal words
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)   # padding = "post"
print(embedded_docs)



[[   0    0    0    0 3078 4788 1119 5159]
 [   0    0    0    0 3078 4788 1119 8531]
 [   0    0    0    0 3078 9415 1119 5156]
 [   0    0    0 3780  181 7375 2522 2723]
 [   0    0    0 3780  181 7375 2522 4397]
 [   0    0    0 9559 3078 7203 1119  994]
 [   0    0    0    0 8691 2571 4567 2522]]


In [42]:
## feature representation
dim = 10



In [51]:
model = Sequential()
model.add(Embedding(voc_size, dim , input_length=sent_length))
model.compile('adam', 'mse')

In [54]:
model.build(input_shape=(None,sent_length))

In [55]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_10 (Embedding)             │ (None, 8, 10)               │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [56]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


array([[[-0.01097182,  0.00308106, -0.01604941, -0.00145613,
          0.02222827, -0.01587565, -0.0329389 ,  0.0293423 ,
         -0.00997084,  0.0305397 ],
        [-0.01097182,  0.00308106, -0.01604941, -0.00145613,
          0.02222827, -0.01587565, -0.0329389 ,  0.0293423 ,
         -0.00997084,  0.0305397 ],
        [-0.01097182,  0.00308106, -0.01604941, -0.00145613,
          0.02222827, -0.01587565, -0.0329389 ,  0.0293423 ,
         -0.00997084,  0.0305397 ],
        [-0.01097182,  0.00308106, -0.01604941, -0.00145613,
          0.02222827, -0.01587565, -0.0329389 ,  0.0293423 ,
         -0.00997084,  0.0305397 ],
        [-0.02972034, -0.01286403,  0.02568189, -0.0164931 ,
         -0.00021937,  0.00188657,  0.00775488, -0.02751314,
          0.01077112, -0.04000316],
        [ 0.0356265 , -0.02151114,  0.00959213,  0.01385703,
          0.01342559,  0.04580336,  0.01339349, -0.03979085,
         -0.03989927,  0.04601747],
        [ 0.04262764,  0.04116825,  0.02245099,  0.0

In [59]:
model.predict(embedded_docs[[0]]) # Pass a 2D array by using slicing

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[[-0.01097182,  0.00308106, -0.01604941, -0.00145613,
          0.02222827, -0.01587565, -0.0329389 ,  0.0293423 ,
         -0.00997084,  0.0305397 ],
        [-0.01097182,  0.00308106, -0.01604941, -0.00145613,
          0.02222827, -0.01587565, -0.0329389 ,  0.0293423 ,
         -0.00997084,  0.0305397 ],
        [-0.01097182,  0.00308106, -0.01604941, -0.00145613,
          0.02222827, -0.01587565, -0.0329389 ,  0.0293423 ,
         -0.00997084,  0.0305397 ],
        [-0.01097182,  0.00308106, -0.01604941, -0.00145613,
          0.02222827, -0.01587565, -0.0329389 ,  0.0293423 ,
         -0.00997084,  0.0305397 ],
        [-0.02972034, -0.01286403,  0.02568189, -0.0164931 ,
         -0.00021937,  0.00188657,  0.00775488, -0.02751314,
          0.01077112, -0.04000316],
        [ 0.0356265 , -0.02151114,  0.00959213,  0.01385703,
          0.01342559,  0.04580336,  0.01339349, -0.03979085,
         -0.03989927,  0.04601747],
        [ 0.04262764,  0.04116825,  0.02245099,  0.0